CREATE DATABASE SERVICE_ITEM_OBAT;
USE SERVICE_ITEM_OBAT;
CREATE TABLE master_data (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    category VARCHAR(255),
    price VARCHAR(255),
    quantity VARCHAR(255)
);